trigger:
  branches:
    include:
      - main
  paths:
    include:
      - /src/*
  tags:
    include:
      - "*.*.*"

pool:
  vmImage: ubuntu-latest

variables:
  - group: LinearB

resources:
  repositories:
    - repository: templates
      type: git
      name: Shared-Assets/Pipeline-Library
      ref: refs/tags/0.5.0

steps:
  - checkout: self
    clean: true
    fetchDepth: 0

  - task: UseDotNet@2
    displayName: "Install .NET SDK from global.json"
    inputs:
      packageType: "sdk"
      useGlobalJson: true

  - task: UseDotNet@2
    displayName: "Install .NET 8.0 SDK"
    inputs:
      packageType: sdk
      version: "8.0.x"

  - pwsh: "./Build.ps1"
    displayName: "Build"

  - task: NuGetAuthenticate@1
    displayName: "NuGet authenticate"

  - task: NuGetCommand@2
    displayName: "NuGet Push"
    inputs:
      command: push
      publishVstsFeed: "gsoft"
      packagesToPush: "./.output/*.nupkg"
      allowPackageConflicts: false

  - template: steps/linearb/linearb-deployment.yaml@templates
    parameters:
      Environment: release
