schedules:
  - cron: "0 12 * * 1-5"
    displayName: "Daily run (except weekend)"
    branches:
      include:
        - main
    # This property ensures that the pipeline is still executed, regardless whether the code has changed or not since the last occurrence.
    always: true

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: self
      type: git
    - repository: templates
      type: git
      name: Shared-Assets/Pipeline-Library
      ref: refs/tags/1.2.7

variables:
  - group: renovate

steps:
  - template: steps/renovate/renovate-template.yml@templates
    parameters:
      githubToken: $(GITHUB_COM_TOKEN)
