trigger:
  branches:
    include:
      - renovate/*

schedules:
  - cron: "32 10 * * 6"
    displayName: "Weekly run"
    branches:
      include: ["main", "master"]
    always: true

resources:
  repositories:
    - repository: templates
      type: git
      name: Shared-Assets/Pipeline-Library
      ref: refs/tags/0.5.0

jobs:
  - template: jobs/semgrep-validation/semgrep-validation-template.yml@templates
    parameters:
      pool: "Azure Pipelines"
