name: 'Install MkCert'
description: 'Install mkcert on Linux, macOS, and Windows'
on:
  workflow_call:  # This allows the workflow to be called from other workflows

runs:
  using: "composite"
  steps:
  - name: Install mkcert on Linux
    if: runner.os == 'Linux'
    run: |
      set -x
      sudo apt update && \
      sudo apt install libnss3-tools -y && \
      sudo apt install mkcert -y && \
      sudo mkcert -install
    shell: bash

  - name: Install mkcert on macOS
    if: runner.os == 'macOS'
    run: |
      set -x
      brew install mkcert && \
      mkcert -install
    shell: bash

  - name: Install mkcert on Windows
    if: runner.os == 'Windows'
    run: |
      choco install mkcert --verbose --yes
      mkcert dummy_arg_to_trigger_certificate_authority_creation
      certutil -addstore "Root" (Join-Path (mkcert -CAROOT) "rootCA.pem")
    shell: pwsh