name: Jira

on:
  pull_request:
    branches: [main]

jobs:
  call-workflow-jira:
    uses: workleap/wl-reusable-workflows/.github/workflows/reusable-jira-workflow.yml@main
    permissions:
      contents: read
      pull-requests: write
      id-token: write