name: Publish

on:
  push:
    branches: ["main"]
    tags: ["*.*.*"]

# We are using OpenID Connect to authenticate with Azure with secret.
# https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: [self-hosted, idp]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Azuze CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Get Secrets from Azure Key Vault
        id: get_secrets
        run: |
          # Set env.ADO_PAT
          ADO_PAT=$(az keyvault secret show --vault-name ${{ vars.IDP_CICD_KEYVAULT_NAME }} --name "gsoft-nuget-feed-ado-pat" --query value -o tsv)
          echo "::add-mask::$ADO_PAT"
          echo "ado_pat=$ADO_PAT" >> $GITHUB_OUTPUT

      - name: Setup .NET 8.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          source-url: ${{ secrets.NUGET_GSOFT_FEED_URL }}
          global-json-file: global.json
        env:
          NUGET_AUTH_TOKEN: ${{ steps.get_secrets.outputs.ado_pat }}

      - run: ./Build.ps1 -SkipTests
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_GSOFT_FEED_URL }}
          NUGET_API_KEY: ${{ steps.get_secrets.outputs.ado_pat }}

  linearb:
    needs: [main]
    uses: workleap/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: 'release'
    permissions:
      id-token: write
      contents: read